excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://prashantpawar.github.io
title:  Prashant Singh Pawar
tagline: A log of everyday life
description: My awesome new site
paginate: 5